---
- name: Create directory for Nginx and PHP
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes
  with_items:
    - "{{ FireLEMP_vol }}/FireLEMP/nginx/php"
    - "{{ FireLEMP_vol }}/FireLEMP/nginx/opcache"
    - "{{ FireLEMP_vol }}/FireLEMP/nginx/php-fpm"
    - "{{ FireLEMP_vol }}/FireLEMP/nginx/nginx/public_html"
    - "{{ FireLEMP_vol }}/FireLEMP/nginx/nginx/log"
    - "{{ FireLEMP_vol }}/FireLEMP/nginx/nginx/conf/conf.d"


- name: Copy template php.ini config file
  template:
    src: php.ini.j2
    dest: "{{ FireLEMP_vol }}/FireLEMP/nginx/php/php.ini"
    owner: root
    group: root
    mode: 0755
    backup: yes


- name: Copy template 10-opcache.ini config file
  copy:
    src: roles/nginx/files/10-opcache.ini
    dest: "{{ FireLEMP_vol }}/FireLEMP/nginx/opcache/10-opcache.ini"
    owner: root
    group: root
    mode: '0755'
    backup: yes

#opcache.memory_consumption=128    (for caching all compiled files)
#opcache.interned_strings_buffer=8
#opcache.max_accelerated_files=4000 (by default can cache 2000 files)
#opcache.revalidate_freq=60
#opcache.fast_shutdown=1
#opcache.enable_cli=1



- name: Copy template www.conf config file
  copy:
    src: roles/nginx/files/www.conf
    dest: "{{ FireLEMP_vol }}/FireLEMP/nginx/php-fpm/www.conf"
    owner: root
    group: root
    mode: '0755'
    backup: yes


- name: Copy template nginx.conf config file
  template:
    src: nginx.conf.j2
    dest: "{{ FireLEMP_vol }}/FireLEMP/nginx/nginx/conf/nginx.conf"
    owner: root
    group: root
    mode: 0755
    backup: yes


- name: Copy template example.com.conf.j2 Nginx vHost config file
  template:
    src: example.com.conf.j2
    dest: "{{ FireLEMP_vol }}/FireLEMP/nginx/nginx/conf/conf.d/{{ domain_name }}.conf"
    owner: root
    group: root
    mode: 0755
    backup: yes


- name: Copy template php-fpm.conf.j2 config file
  template:
    src: php-fpm.conf.j2
    dest: "{{ FireLEMP_vol }}/FireLEMP/nginx/nginx/conf/conf.d/php-fpm.conf"
    owner: root
    group: root
    mode: 0755
    backup: yes


- name: Copy template index.html file
  template:
    src: index.html.j2
    dest: "{{ FireLEMP_vol }}/FireLEMP/nginx/nginx/public_html/index.html"
    owner: root
    group: root
    mode: 0755
    backup: yes


#- name: Copy template php file
#  template:
#    src: info.php.j2
#    dest: "{{ FireLEMP_vol }}/FireLEMP/nginx/nginx/public_html/info.php"
#    owner: root
#    group: root
#    mode: 0755
#    backup: yes
