- name: Creates directory for PHP config file
  file:
    path: "{{ FireLEMP_vol }}/php"
    state: directory
    owner: root
    group: root
    mode: 0775
    #recurse: yes

- name: Creates directory for OPcache config file
  file:
    path: "{{ FireLEMP_vol }}/opcache"
    state: directory
    owner: root
    group: root
    mode: 0775
    #recurse: yes

- name: Creates directory for php-fpm config file
  file:
    path: "{{ FireLEMP_vol }}/php-fpm"
    state: directory
    owner: root
    group: root
    mode: 0775
    #recurse: yes

- name: Copy template php.ini config file
  template:
    src: php.ini.j2
    dest: "{{ FireLEMP_vol }}/php/php.ini"
    owner: root
    group: root
    mode: 0755
    backup: yes

- name: Copy template 10-opcache.ini config file
  template:
    src: 10-opcache.ini.j2
    dest: "{{ FireLEMP_vol }}/opcache/10-opcache.ini"
    owner: root
    group: root
    mode: 0755
    backup: yes

- name: Copy template www.conf config file
  template:
    src: www.conf.j2
    dest: "{{ FireLEMP_vol }}/php-fpm/www.conf"
    owner: root
    group: root
    mode: 0755
    backup: yes
