---
- name: install packages
  apt:
    update_cache: yes
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common


- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable


- name: Install Docker CE
  apt:
    update_cache: yes
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    

- name: start and enable docker service
  systemd:
    state: started
    enabled: yes
    name: docker
