---
- name: Check out distribution and install python version 2 on Ubuntu hosts
  raw: DISTRO=$(awk '/^ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }') && if [ "$DISTRO" == "ubuntu" ] ; then apt-get -y update && apt-get install -y python-minimal; fi

- name: enable gather_facts
  setup:



#tasks on CentOS or RHEL distribution
- name: Install or update packages on RPM Linux distribution
  include: 'rpm-packages.yml'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'



#- include: 'docker-installation.yml'
