---
- name: Check out distribution and install python version 2 on Ubuntu hosts
  raw: DISTRO=$(awk '/^ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }') && if [ "$DISTRO" == "ubuntu" ] ; then apt-get -y update && apt-get install -y python-minimal; fi

- name: enable gather_facts
  setup:



#tasks on CentOS or RHEL distribution
- name: Install or update packages on RPM Linux distribution
  include: 'rpm-packages.yml'
  include: 'rpm-docker-installation.yml'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'



#-












- name: Create a network with custom IPAM config
  docker_network:
    name: FireLEMP-net
    ipam_config:
      - subnet: 172.70.0.0/16
        gateway: 172.70.0.1
