---
- name : install epel repo
  dnf:
    name:
      - epel-release

- name : install packages
  dnf:
    name:
      - zip
      - unzip
      - mtr
      - nload
      - screen
      - nmap
      - rsync
      #- glances
      - htop
      - nethogs
      - nano
      - wget
      - net-tools
      - open-vm-tools
      - bash-completion
      - kernel-devel
      - kernel-headers
      - hdparm
      - iotop
      - bind-utils
      #- whois
      - vim
      - telnet
      #- libselinux-python
      - tcpdump
      - xz
      - git
      - yum-utils
      - lsof
      - aria2
      - psmisc
      - python3-pip
      - curl
      - dnf-plugins-core
    state: latest


- name: upgrade all packages
  dnf:
    name: "*"
    state: latest
