---
# Install docker-ce
- name: Download official Docker repository file
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: install docker-ce packages
  shell: dnf install docker-ce --nobest -y


- name: start and enable docker service
  systemd:
    state: started
    enabled: yes
    name: docker
