---
#configure sysctl.conf file
- name: configure sysctl.conf file
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    backup: yes

#apply sysctl config
- name: apply sysctl config
  command:  sysctl -p
