---
- name: Creates directory for Varnish config file
  file:
    path: "{{ FireLEMP_vol }}/FireLEMP/varnish/conf"
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: Copy template default.vcl Varnish config file
  template:
    src: default.vcl.j2
    dest: "{{ FireLEMP_vol }}/FireLEMP/varnish/conf/default.vcl"
    owner: root
    group: root
    mode: 0755
    backup: yes
