---
- name: Creates directory for MariaDB data
  file:
    path: "{{ FireLEMP_vol }}/FireLEMP/mariadb/data"
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: Creates directory for MariaDB config file
  file:
    path: "{{ FireLEMP_vol }}/FireLEMP/mariadb/conf.d"
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: Creates directory for MariaDB log files
  file:
    path: "{{ FireLEMP_vol }}/FireLEMP/mariadb/log"
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes
