---
#- name: Creates directory for Prometheus node_exporter
#  file:
#    path: "{{ FireLEMP_vol }}/FireLEMP/prometheus/node_exporter"
#    state: directory
#    owner: prometheus
#    group: prometheus
#    mode: 0775


#- name: Download prometheus node exporter binary
#  get_url:
#    url: "https://github.com/prometheus/node_exporter/releases/download/{{ prometheus_node_exporter_version }}/{{ prometheus_node_exporter_release_name }}"
#    dest: "{{ FireLEMP_vol }}/FireLEMP/prometheus/node_exporter"


- name: Download and Unarchive prometheus node_exporter file with extra options
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/{{ prometheus_node_exporter_version }}/{{ prometheus_node_exporter_release_name }}"
    dest: "{{ FireLEMP_vol }}/FireLEMP/prometheus/node_exporter"
    creates: "{{ FireLEMP_vol }}/FireLEMP/prometheus/node_exporter"
    remote_src: yes
    owner: prometheus
    group: prometheus
    mode: 0755
    extra_opts:
    - [--strip-components=1]


- name: Remove file "{{ prometheus_node_exporter_release_name }}" (delete file)
  file:
    path: "{{ FireLEMP_vol }}/FireLEMP/prometheus/node_exporter/{{ prometheus_node_exporter_release_name }}"
    state: absent


- name: Add node_exporter systemd file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    backup: yes
    

- name: just force systemd to reread configs, start and enable node_exporter service
  systemd:
    daemon_reload: yes
    state: started
    enabled: yes
    name: node_exporter
